// Import helpers
import readFile from './readFile';

/**
 * Read a JSON file into a JavaScript object.
 * @author Jay Luker
 * @param filePath path to the JSON file.
 * @returns the object generated by parsing the JSON file.
 */
const readJson = (filePath: string): { [k: string]: any } => {
  return JSON.parse(readFile(filePath));
};

export default readJson;
