import readFile from './readFile.js';

/**
 * Read a JSON file into a JavaScript object.
 * @author Jay Luker
 * @param {string} filePath path to the JSON file.
 * @returns {Record<string, any>} the object generated by parsing the JSON file.
 */
const readJson = (filePath: string): Record<string, any> => {
  return JSON.parse(readFile(filePath));
};

export default readJson;
